### ISSUE TITLE
Don't use "Scratch" in the name.

### ISSUE THREAD

**Issue by UniqueName12345** [imlanky/smc#6]
Scratch is a trademark of the MIT group, and as such, you need to ask them if you can use their name for your product. So I would suggest either asking permission or renaming SMC.

**Comment by imlanky** [comment]
ok

**Comment by imlanky** [comment]
![image](https://user-images.githubusercontent.com/116201516/196941334-64670709-e89d-467d-a862-369ebcfefa5c.png)
updating soon
